language: perl
perl:
  - blead
  - dev
#  No clean build due to removal of '.' from lib path
  - 5.40
  - 5.38
  - 5.36
  - 5.34
  - 5.32
  - 5.30
  - 5.28
  - 5.26
  - 5.24
  - 5.22
  - 5.20
  - 5.18
  - 5.16
#  stopping builds; is anyone really still using this version?
#  - 5.14
#  - 5.12
#  - 5.10
#  - 5.8
matrix:
  include:
    - perl: 5.40
      env: COVERAGE=1
  allow_failures:
    - perl: blead
    - perl: blead-thr
    - perl: dev
sudo: false
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpanm -n -f Pod::Coverage::TrustPod Test::Perl::Critic Test::Pod::Coverage Test::Pod
